#服务器配置
server:
  port: 8000
  context-path: "/ball-data"
  tomcat:
    basedir:  "ball-tomcat"
    uri-encoding: "UTF-8"
    max-connections: 20000
    max-threads: 1000


#指定mybatis映射文件的地址
mybatis:
  config-location: "classpath:mybatis/mybatis-config.xml"

ribbon:
  ReadTimeout: 60000  
  ConnectTimeout: 60000
  MaxTotalConnections: 200
  MaxConnectionsPerHost: 200

logging:
  config: classpath:log4j2.xml
  level:
    root: "INFO"

spring:
  application:
    name: "ball-data"
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ball
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver