#服务器配置
server:
  port: 8000
  context-path: "/ball-data"
  tomcat:
    basedir:  "ball-tomcat"
    uri-encoding: "UTF-8"
    max-connections: 20000
    max-threads: 1000
    
ribbon:
  ReadTimeout: 60000  
  ConnectTimeout: 60000
  MaxTotalConnections: 200
  MaxConnectionsPerHost: 200

logging:
  level:
    root: "INFO"

spring:
  application:
    name: "ball-data"